TVquVWSbKDr9Aeo4nuf2Tycq3cpQTM3cnP# This is a basic workflow to help you get started with Actions

name: README.md

https://github.com/tronscan/tron-tvc-list# Controls when the workflow will run
on:TVquVWSbKDr9Aeo4nuf2Tycq3cpQTM3cnP[![.github/workflows/blank.yml](https://github.com/Alaa3l/tron-tvc-list/actions/workflows/blank.yml/badge.svg?branch=main)](https://github.com/Alaa3l/tron-tvc-list/actions/workflows/blank.yml)https://github.com/Alaa3l/tron-tvc-list/actions/workflows/blank.yml/badge.svg?branch=mainhttps://github.com/tronscan/tron-tvc-list
  # Tr0xf83a27f09e59fb389824a7a2d5df071aa79c1f9figgers the workflow on push or pull request events but only for the "main" branch
,
    branches: [ "https://www.bybit.com/invite?ref=PBX2LP" ]
  pull_request:
    branches: [ "TVquVWSbKDr9Aeo4nuf2Tycq3cpQTM3cnP" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
TVquVWSbKDr9Aeo4nuf2Tycq3cpQTM3cnP# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:0xf83a27f09e59fb389824a7a2d5df071aa79c1f9f
  # This workflow contains a single job called "build"
  build:TVquVWSbKDr9Aeo4nuf2Tycq3cpQTM3cnP
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # CheTBgbdQQPPGxCg7NhFfQRWqh8SFRCuRPuRocks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
TZ3ktDuTmTvV1Sv4pX6dbhPioeEx9ULgTj
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
